### ISSUE TITLE
Sets up IPv6 address which blackholes all IPv6 traffic

### ISSUE THREAD

**Issue by cjdelisle** [dkoukoul/pkt_vpn_client#2]
The VPN server doesn't correctly support IPv6 and yet it is issuing IPv6 addresses to the client which is causing the client to become unable to reach IPv6 based services so things like installing software hang indefinitely.

For the moment, lets just make the server stop issuing IPv6 addresses, we should fix IPv6 forwarding but it's challenging to do right because what we really want to do is issue *entire* IPv6 ranges to each client, not just forward ports.

**Comment by dkoukoul** [comment]
this will be resolved on the anodevpn-server
