### ISSUE TITLE
The client has no reason to use nftables

### ISSUE THREAD

**Issue by cjdelisle** [dkoukoul/pkt_vpn_client#3]
On my server, I saw:

Error adding port 3000 to nftables: error executing command: exit status 127, output: sh: nft: not found

I don't happen to have nft on this machine, there is no firewall. This is not the job of the VPN client to punch a hole in a firewall, it should leave the firewall alone. If the client has a firewall rule which is dropping traffic, that's the fault of the person setting it up.

**Comment by dkoukoul** [comment]
You are right, I had added that during the tests, but it should be removed. Thanks
