### ISSUE TITLE
Some kind of check for port allocated which shouldn't be happening

### ISSUE THREAD

**Issue by cjdelisle** [dkoukoul/pkt_vpn_client#4]
I'm not sure what this is, but there's no reason to check anything related to the port on the client side. We need to check on the SERVER side that we have not already issued the port to someone else, but on the client side, if the port is bound that's normal because I setup my server and *then* I run the VPN client.

```
Choose a server by number: 11
Choose a port for reverse VPN (empty to skip): 3000
3000
Error checking port 3000: exec: "bash": executable file not found in $PATH
This port is already allocated.
Are you sure you want to use this port? (y/n) y
```

**Comment by dkoukoul** [comment]
good point, I thought it might be useful to notify the user, but you are right there is no point for that on the client side.
